# Generated by Django 5.2.6 on 2025-11-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiftyOptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateField()),
                ('strike', models.FloatField()),
                ('option_type', models.CharField(max_length=10)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('open_interest', models.FloatField(blank=True, null=True)),
                ('iv', models.FloatField(blank=True, null=True)),
                ('expiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ts.niftyexpiry')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('expiry', 'strike', 'option_type', 'fetch_date')},
            },
        ),
    ]
