# Generated by Django 4.0.5 on 2022-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0009_ledger_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
