# Generated by Django 4.0.1 on 2022-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0018_alter_claimedproduct_id_alter_extraitems_id_and_more'),
        ('pis_sales', '0012_alter_saleshistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='extra_items',
            field=models.ManyToManyField(blank=True, max_length=200, to='pis_product.ExtraItems'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, max_length=100, to='pis_product.PurchasedProduct'),
        ),
    ]
