# Generated by Django 5.2.6 on 2025-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('previousClose', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('dayHigh', models.FloatField(blank=True, null=True)),
                ('dayLow', models.FloatField(blank=True, null=True)),
                ('lastPrice', models.FloatField(blank=True, null=True)),
                ('High', models.FloatField(blank=True, null=True)),
                ('Low', models.FloatField(blank=True, null=True)),
                ('Range', models.FloatField(blank=True, null=True)),
                ('Gap', models.FloatField(blank=True, null=True)),
                ('Change', models.FloatField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nifty_data',
                'ordering': ['-date'],
            },
        ),
    ]
